dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - travis_wait 680 docker build -t  $DOCKER_USERNAME/firedrake-complex firedrake-complex
        - travis_wait 680 docker push $DOCKER_USERNAME/firedrake-complex
